close all
clear all

%% setpath for rest of specific functions

addpath('/home/pbrown/Documents/MATLAB/DICE/test_Burke/DICE_Burke_Damage_growth')

%% decide on type of experiment 

global T
T = 65;

global abatement_cost_on
abatement_cost_on = 1;  %1 means there is an abatement cost and 0 means there is not 

global Burke_damage_on;
Burke_damage_on = 1;  %1 means Burke damage through TFP and capital depreciation pathways, 
                      %0 means default DICE, 
                      %2 means no damage
                      
global optimize_on;
optimize_on = 1;  %1 means optimizing, 0 means its being forced by a specified control rate

     if optimize_on == 0
         
         global aopt
         aopt = zeros(T,1);
         
     end

global optimize_for_total_utility;
optimize_for_total_utility = 1; %1 means optimize for total utility, 0 means optimize for per-capita utility

global utility_function;
utility_function = 1; %1 means utility function in code and 0 means utility function in text,

%% run main program

global damage_dep_rate_coeff_on_T
global damage_TFP_growth_coeff_on_T
global elasmu
global Sigg0
global Siggd
global pd
global theta2
global LA
global Ag0
global Agd
global prstp
global deltaT

damage_dep_rate_coeff_on_T = 0.007;
damage_TFP_growth_coeff_on_T = 0.002;
elasmu = 1.45;
Sigg0 = -0.0152;
Siggd = -0.001;
pd = 0.025;    
theta2 = 2.6;
LA = 11500;
Ag0 = 0.076;
Agd = 0.005;
prstp = 0.015;
deltaT = 3.1;

var_names = {'damage cap-dep-rate coeff on T',...
             'damage TFP coeff on T',...
             'elasticity of utility',...
             'C intensity, growth rate',...
             'C intensity, change in growth rate',...
             'backstop cost decline',...
             'abatement cost curve exponent',...
             'asymptotic population',...
             'TFP, growth rate',...
             'TFP, change in growth rate',...
             'pure rate of time preference',...
             'climate sensitivity'};
                           
overall_plot_series_all = [];

%run DICE
addpath(genpath('/home/pbrown/Documents/MATLAB/DICE/test_Burke/DICE_Burke_Damage_growth'))
    DICE;

%Calculate the shadow Carbon Price
opt_price = pbacktime.*(aopt'./pai(1:length(aopt))).^(theta2-1); % Carbon price, $ per ton of CO2

overall_plot_series = cat(1,S(16,:),...
                S(17,:),...
                S(7,:),...
                S(19,:),...
                S(9,:),...
                Sig,...
                L,...
                R,...
                S(20,:),...
                S(12,:),...
                S(4,:),...
                S(2,:),...
                S(14,:),...
                aopt',...
                opt_price,...
                S(10,:));

            overall_plot_series_all = cat(3,overall_plot_series_all,overall_plot_series);

% This is what is in "S":
    % 1 - regular capital 
    % 2 - GMST 
    % 3 - lower ocean temperature 
    % 4 - atmospheric CO2 
    % 5 - upper ocean CO2 
    % 6 - lower ocean CO2 
    % 7 - gross output 
    % 8 - zero-carbon emissions captial (leave NaN)
    % 9 - total capital (same as 1)
    % 10 - abatement cost
    % 11 - epsilon (leave NaN)
    % 12 - Industrial CO2 emissions
    % 13 - CO2 Radiative Forcing
    % 14 - Climate Damage
    % 15 - 
    % 16 - total utility
    % 17 - per capita utility
    % 18 - consumption
    % 19 - consumption per capita
    % 20 - net output
    % 21 - deltaK
    % 22 - TFP growth
    % 23 - TFP
      
% add Output/capita = $ million/person
    per_capita_GDP_million_per_person = overall_plot_series_all(9,:,:)./overall_plot_series_all(7,:,:);
    %convert to thousand / person
    per_capita_GDP_thousand_per_person = (1000).*per_capita_GDP_million_per_person;

overall_plot_series_all = cat(1,overall_plot_series_all,per_capita_GDP_thousand_per_person);

titles = {'total utility',...
          'per-capita utility',...
          'gross output',...
          'per-capita consumption',...
          'total capital',...
          'CO_2 intensity of output',...
          'population',...
          'discount factor',...
          'net output (Y_G)',...
          'industrial CO_2 emissions',...
          'ATM CO_2',...
          'global temperature',...
          'damage from warming fraction',...
          'control rate',...
          'carbon tax',...
          'abatement cost fraction',...
          'per-capita GWP'};
      
ylabels = {'utils',...
          'utils / person',...
          '$ trillion 2010 USD',...
          '$ thousand 2010 USD / person',...
          '$ trillion 2010 USD',...
          'MTC/$1000',...
          'million people',...
          'fraction',...
          '$ trillion 2010 USD',...
          'Gt CO_2 / year',...
          'Gt CO_2',...
          '\Delta T above PI',...
          'frac output w.r.t. no warming',...
          'fraction',...
          '$1000 / Ton CO_2',...        
          'fract output w.r.t. no abatement',...
          '$ thousand 2010 USD / person'};

aopt_no_damage_no_mitigation = aopt;
overall_plot_series_all_no_damage_no_mitigation = overall_plot_series_all;
titles_no_damage_no_mitigation = titles;
ylabels_no_damage_no_mitigation = ylabels;
