close all
clear all

%% setpath for rest of specific functions

addpath('/home/pbrown/Documents/MATLAB/DICE/test_Burke/DICE_Burke_Damage_growth')

%% load the optimized runs

abatement_cost_on = 1;
Burke_damage_on = 0;
optimize_on = 1;
optimize_for_total_utility = 1;
utility_function = 1;

code_string = ['_a',num2str(abatement_cost_on),...
                     '_B',num2str(Burke_damage_on),...
                     '_o',num2str(optimize_on),...
                     '_u',num2str(optimize_for_total_utility),...
                     '_uf',num2str(utility_function)];
                 
% strcat('overall_plot_series_',code_string) = overall_plot_series;
% strcat('NPV_utility_',code_string) = NPV_utility;

      load(['/home/pbrown/Documents/MATLAB/DICE/test_Burke/scale_with_temperature_Burke_damage_aopt',code_string,'.mat'],...
          'aopt_time_series',...
          'overall_plot_series_all',...
          'titles',...
          'ylabels',...
          'code_string')
      
            overall_plot_series_all_default_DICE_opt = overall_plot_series_all;

            
%DICE Burke
            
abatement_cost_on = 1;
Burke_damage_on = 1;
optimize_on = 1;
optimize_for_total_utility = 1;
utility_function = 1;

code_string = ['_a',num2str(abatement_cost_on),...
                     '_B',num2str(Burke_damage_on),...
                     '_o',num2str(optimize_on),...
                     '_u',num2str(optimize_for_total_utility),...
                     '_uf',num2str(utility_function)];
                 
% strcat('overall_plot_series_',code_string) = overall_plot_series;
% strcat('NPV_utility_',code_string) = NPV_utility;

      load(['/home/pbrown/Documents/MATLAB/DICE/test_Burke/scale_with_temperature_Burke_damage_aopt',code_string,'.mat'],...
          'aopt_time_series',...
          'overall_plot_series_all',...
          'titles',...
          'ylabels',...
          'code_string')
      
            overall_plot_series_all_Burke_opt = overall_plot_series_all;
            
            
            
%% load the exogenously forced runs

time_desc = 2015:5:2335;

%load DICE-default

abatement_cost_on = 1;
Burke_damage_on = 0;
optimize_on = 0;
optimize_for_total_utility = 1;
utility_function = 1;

code_string = ['_a',num2str(abatement_cost_on),...
                     '_B',num2str(Burke_damage_on),...
                     '_o',num2str(optimize_on),...
                     '_u',num2str(optimize_for_total_utility),...
                     '_uf',num2str(utility_function)];
                 
load(['/home/pbrown/Documents/MATLAB/DICE/test_Burke/scale_with_temperature_Burke_damage_aopt',code_string,'.mat'],...
          'opt_temp_i_1',...
          'aopt_time_series',...
          'overall_plot_series_all',...
          'R',...
          'titles',...
          'ylabels',...
          'code_string',...
          'end_year_plot',...
          'end_year_calc_1',...
          'end_year_calc_2',...
          'end_year_plot_ind',...
          'end_year_calc_ind_1',...
          'end_year_calc_ind_2',...
          'two_d_plot_trimmed_1',...
          'two_d_plot_trimmed_2',...
          'two_d_plot_trimmed_discounted_1',...
          'two_d_plot_trimmed_discounted_2',...
          'integrated_net_GDP_1',...
          'integrated_net_GDP_2')
      
      overall_plot_series_all_default_DICE = overall_plot_series_all;
      
      %load Burke damage
abatement_cost_on = 1;
Burke_damage_on = 1;
optimize_on = 0;
optimize_for_total_utility = 1;
utility_function = 1;

code_string = ['_a',num2str(abatement_cost_on),...
                     '_B',num2str(Burke_damage_on),...
                     '_o',num2str(optimize_on),...
                     '_u',num2str(optimize_for_total_utility),...
                     '_uf',num2str(utility_function)];
                 
load(['/home/pbrown/Documents/MATLAB/DICE/test_Burke/scale_with_temperature_Burke_damage_aopt',code_string,'.mat'],...
          'opt_temp_i_1',...
          'aopt_time_series',...
          'overall_plot_series_all',...
          'R',...
          'titles',...
          'ylabels',...
          'code_string',...
          'end_year_plot',...
          'end_year_calc_1',...
          'end_year_calc_2',...
          'end_year_plot_ind',...
          'end_year_calc_ind_1',...
          'end_year_calc_ind_2',...
          'two_d_plot_trimmed_1',...
          'two_d_plot_trimmed_2',...
          'two_d_plot_trimmed_discounted_1',...
          'two_d_plot_trimmed_discounted_2',...
          'integrated_net_GDP_1',...
          'integrated_net_GDP_2')
      
      overall_plot_series_all_Burke = overall_plot_series_all;
      
      T = 65;
     
      
%% plot tight

titles{16} = 'Cost of climate change mitigation';
titles{13} = 'Cost of climate change (damages)';
titles{12} = 'Global Temperature';
titles{10} = 'CO_2 emissions';
titles{9} = 'Gross World Product';
titles{17} = 'Gross World Product per capita';

ylabels{16} = 'Percent of Gross World Product';
ylabels{13} = 'Percent of Gross World Product';
ylabels{12} = 'Temperature above preindustrial (C)';
ylabels{9} = 'Trillions of 2010 US$';
ylabels{17} = 'Thousands of 2010 US$ per capita';

marker_colors = {'k','r'};

good_time_ind = find(time_desc == 2100);

sub_var_inds = [14 10 12 16 13 9];

y_maxs = [ 1.3 100 6 0.4 0.4 1800];
y_mins = [0 -25 0 0 0 0];

num_scens = size(overall_plot_series_all_default_DICE,3);

row_num = 2;
col_num = 3;

end_year_plot = 2140;

    FigHandle = figure('Position', [100, 100, 700, 300]); %[left bottom width height]
    set(gcf,'color',[1 1 1]);
    set(0, 'DefaultAxesFontSize',6);
    set(0,'defaultAxesFontName', 'helvetica')
    hold on
    
for var_i = 1:length(sub_var_inds)
    
    subplot(row_num,col_num,var_i)
    hold on
    
    %plot default-DICE
        for exp_i = 1:num_scens
    
            if var_i ~= 5; plot(time_desc,squeeze(overall_plot_series_all_default_DICE(sub_var_inds(var_i),:,exp_i)),...
                    '-k','LineWidth',0.5); end
            if var_i == 5; plot(time_desc,-1*squeeze(overall_plot_series_all_default_DICE(sub_var_inds(var_i),:,exp_i)-1),...
                    '-k','LineWidth',0.5); end
        
        end
        
        
    %plot Burke
        for exp_i = 1:num_scens
    
            if var_i ~= 5; plot(time_desc,squeeze(overall_plot_series_all_Burke(sub_var_inds(var_i),:,exp_i)),...
                    '--r','LineWidth',0.5); end
            if var_i == 5; plot(time_desc,-1*squeeze(overall_plot_series_all_Burke(sub_var_inds(var_i),:,exp_i)-1),...
                    '--r','LineWidth',0.5); end
        
        end
        
            if var_i ~= 5; plot(time_desc,squeeze(overall_plot_series_all_default_DICE_opt(sub_var_inds(var_i),:)),...
                    '-b','LineWidth',1); end
            if var_i == 5; plot(time_desc,-1*squeeze(overall_plot_series_all_default_DICE_opt(sub_var_inds(var_i),:)-1),...
                    '-b','LineWidth',1); end
        
            if var_i ~= 5; plot(time_desc,squeeze(overall_plot_series_all_Burke_opt(sub_var_inds(var_i),:)),...
                    '-m','LineWidth',1); end
            if var_i == 5; plot(time_desc,-1*squeeze(overall_plot_series_all_Burke_opt(sub_var_inds(var_i),:)-1),...
                    '-m','LineWidth',1); end        

        plot([2100 2100],[y_mins(var_i) y_maxs(var_i)],':k','LineWidth',0.5)
        
        xlim([2015 end_year_plot])
        ylim([y_mins(var_i) y_maxs(var_i)])
        

        xlabel('Year')
        ylabel(ylabels{sub_var_inds(var_i)})
        title(titles{sub_var_inds(var_i)})

end

%print(gcf,'/home/pbrown/Documents/MATLAB/DICE/test_Burke/time_series_tight_temp_targets','-dpdf','-bestfit')
print(gcf,'/home/pbrown/Documents/MATLAB/DICE/test_Burke/time_series_tight_temp_targets_control_rates','-dpdf','-bestfit')



      